default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: monosumida_development

test:
  <<: *default
  database: monosumida_test

production:
  <<: *default
  database: monosumida_production
  adapter: postgresql
  encoding: unicode
